"""Derive a flat-ground ELF3 MuJoCo model from the vendor MJCF.

The vendor `elf3.xml` includes depth cameras, a lidar and a large obstacle
course. Training runs on a flat plane, so sim2sim must too -- otherwise the
comparison measures terrain, not the policy. This script strips those includes
and substitutes a plain ground plane and light, leaving everything else (link
inertias, joint limits, armature, capsule collisions, IMU site) untouched.

The vendor file stays pristine as the source of record.

    python MujocoDeploy/make_elf3_flat.py
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path


MODEL_DIR = Path(__file__).resolve().parent / "elf3_description"
VENDOR_XML = MODEL_DIR / "elf3.xml"
FLAT_XML = MODEL_DIR / "elf3_flat.xml"

GROUND = """
  <asset>
    <texture name="groundplane" type="2d" builtin="checker" mark="edge"
             rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3" markrgb="0.8 0.8 0.8"
             width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true"
              texrepeat="5 5" reflectance="0.1"/>
  </asset>
  <worldbody>
    <light pos="0 0 3" dir="0 0 -1" directional="true"/>
    <geom name="floor" type="plane" size="0 0 0.05" material="groundplane"
          contype="1" conaffinity="1" condim="3"/>
  </worldbody>
"""


def main() -> int:
    if not VENDOR_XML.is_file():
        print(f"error: vendor MJCF not found at {VENDOR_XML}", file=sys.stderr)
        return 1

    tree = ET.parse(VENDOR_XML)
    root = tree.getroot()

    # Drop the sensor-rig and terrain includes; keep the robot itself.
    removed = []
    for parent in [root] + list(root.iter()):
        for include in list(parent.findall("include")):
            removed.append(include.get("file"))
            parent.remove(include)
    if not removed:
        print("warning: no <include> elements found; is this the vendor file?")

    # Splice in flat ground. Parsing a fragment keeps the indentation sane.
    ground = ET.fromstring(f"<root>{GROUND}</root>")
    for section in ground:
        existing = root.find(section.tag)
        if existing is None:
            root.append(section)
        else:
            for child in section:
                existing.append(child)

    ET.indent(tree, space="  ")
    header = (
        "<!-- Generated by MujocoDeploy/make_elf3_flat.py from elf3.xml.\n"
        "     Do not edit: regenerate instead. Flat ground, no cameras or\n"
        f"     lidar, so sim2sim matches the flat-plane training terrain.\n"
        f"     Removed includes: {', '.join(removed)} -->\n"
    )
    FLAT_XML.write_text(header + ET.tostring(root, encoding="unicode"))

    print(f"removed {len(removed)} includes:")
    for name in removed:
        print(f"  {name}")
    print(f"wrote {FLAT_XML}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
